### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by Silverarmor** [Silverarmor/j4dash#1]
# FEATURES
- [x] event end times if past 9pm.
- [ ] dark mode/background image
- [ ] chores
- [ ] Allow multiuser events. e.g. AB & CD - Event Name

# BUGS

- [x] fix day
- [x] weather broken
